books/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


app_name = 'books'

router = routers.DefaultRouter()
router.register('', views.VolumeApiView, 'Volume')

urlpatterns = [
    path('', views.volumes_list, name='list'),
    path('add_volume/', views.AddVolumeView.as_view(), name='add_volume'),
    path('import/', views.ImportVolumesView.as_view(), name='import'),
    path('import_action/<str:query>/', views.import_action, name='import_action'),
    path('api/', include(router.urls)),
]

booksman/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
]

books/models.py
from django.db import models
from django_mysql.models import JSONField


class Volume(models.Model):
    title = models.CharField(max_length=255)
    publishedDate = models.DateField(null=True, blank=True)
    pageCount = models.PositiveIntegerField()
    imageLinks = JSONField()
    language = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=255)
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, related_name='authors')

    def __str__(self):
        return self.name


class IndustryIdentifier(models.Model):
    TYPE_CHOICES = (
        ('ISBN_10', 'ISBN_10'),
        ('ISBN_13', 'ISBN_13'),
        ('ISSN', 'ISSN'),
        ('OTHER', 'OTHER'),
    )
    type = models.CharField(choices=TYPE_CHOICES, max_length=7)
    identifier = models.CharField(max_length=255)
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE, related_name='industryIdentifiers')

    def __str__(self):
        return self.identifier

books/forms.py
from django import forms

from .models import Volume, IndustryIdentifier, Author


class SearchForm(forms.Form):
    CHOICES = [
        ('title', 'Title'),
        ('authors', 'Authors'),
        ('language', 'Language'),
        ('pubdate', 'Published Date (year or start-end)'),
    ]
    pattern = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))
    search_by = forms.ChoiceField(choices=CHOICES, label='Search by')


class AddVolumeForm(forms.ModelForm):
    class Meta:
        model = Volume
        fields = ['title', 'publishedDate', 'pageCount', 'language']
        labels = {
            'publishedDate': 'Published Date',
            'pageCount': 'Page Count',
            'imlink_sm': 'ImageLink Small Thumbnail',
            'imlink': 'ImageLink Thumbnail',
        }
        help_texts = {
            'publishedDate': 'YYYY-MM-DD',
        }

    imlink = forms.URLField(required=False, label='ImageLink Thumbnail')
    imlink_sm = forms.URLField(required=False, label='ImageLink Small Thumbnail')


IndustryIdentifierFormset = forms.inlineformset_factory(
    Volume, IndustryIdentifier,
    fields=['type', 'identifier'],
    extra=2,
    max_num=2,
    can_delete=False,
)


AuthorFormset = forms.inlineformset_factory(
    Volume, Author,
    fields=['name'],
    extra=2,
    max_num=2,
    can_delete=False,
)


class ImportQueryForm(forms.Form):
    query = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))

books/views.py
from datetime import datetime as dt

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views import View
from django.views.decorators.http import require_http_methods
from rest_framework import viewsets
from rest_framework.filters import SearchFilter

from .models import Volume, Author, IndustryIdentifier
from .forms import SearchForm, AddVolumeForm, IndustryIdentifierFormset, AuthorFormset, ImportQueryForm
from .serializers import VolumeSerializer

from libs.volumes_import import get_volumes


def volumes_list(request):
    vol_count = Volume.objects.count()
    volumes = None

    if request.method == 'GET':
        form = SearchForm()

    elif request.method == 'POST':
        form = SearchForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            pattern = cd['pattern']
            search_by = cd['search_by']

            if search_by == 'title':
                volumes = Volume.objects.filter(title__icontains=pattern)

            elif search_by == 'authors':
                volumes = Volume.objects.filter(authors__name__icontains=pattern)

            elif search_by == 'language':
                volumes = Volume.objects.filter(language__iexact=pattern)

            elif search_by == 'pubdate':
                if '-' in pattern:
                    year_start, year_end = pattern.split('-')
                    if not year_end:
                        year_end = dt.now().year

                    date_filter = Q(publishedDate__year__gte=year_start, publishedDate__year__lte=year_end)
                else:
                    date_filter = Q(publishedDate__year=pattern)

                volumes = Volume.objects.filter(date_filter)

    context = {
        'form': form,
        'vol_count': vol_count,
        'volumes': volumes,
    }
    return render(request, 'books/books_list.html', context)


class AddVolumeView(View):
    def get(self, request):
        form = AddVolumeForm()
        formset_indident = IndustryIdentifierFormset()
        formset_author = AuthorFormset()

        context = {
            'form': form,
            'formset_indident': formset_indident,
            'formset_author': formset_author,
        }
        return render(request, 'books/add_volume.html', context)

    def post(self, request):
        form = AddVolumeForm(request.POST)

        if form.is_valid():
            volume = form.save(commit=False)
            image_links = {
                'smallThumbnail': form.cleaned_data['imlink_sm'],
                'thumbnail': form.cleaned_data['imlink'],
            }
            volume.imageLinks = image_links
            volume.save()

            if volume:
                formset_indident = IndustryIdentifierFormset(request.POST, instance=volume)
                if formset_indident.is_valid():
                    formset_indident.save()

                formset_author = AuthorFormset(request.POST, instance=volume)
                if formset_author.is_valid():
                    formset_author.save()

        return redirect('books:list')


class ImportVolumesView(View):
    def get(self, request):
        form = ImportQueryForm()
        return render(request, 'books/import.html', {'form': form})

    def post(self, request):
        query = request.POST['query']
        if query:
            num_of_volumes = get_volumes(query, check_only=True)
            return HttpResponse(num_of_volumes)

        return HttpResponse(None)


@require_http_methods(['GET'])
def import_action(request, query):
    def validate_item_data(raw_data):
        # publishedDate
        if 'publishedDate' in raw_data:
            published_date = raw_data['publishedDate']
            # if missing month and day
            if len(published_date) == 4:
                published_date = f'{published_date}-01-01'
            # if missing day
            elif len(published_date) == 7:
                published_date = f'{published_date}-01'
        else:
            # if no date
            published_date = None

        # imageLinks
        image_links = {'smallThumbnail': '', 'thumbnail': ''}
        if 'imageLinks' in raw_data:
            image_links['thumbnail'] = raw_data['imageLinks']['thumbnail']
            image_links['smallThumbnail'] = raw_data['imageLinks']['smallThumbnail']

        data = {
            'publishedDate': published_date,
            'imageLinks': image_links,
            'title': raw_data['title'].strip(),
            'language': raw_data['language'],
            'pageCount': raw_data['pageCount'] if 'pageCount' in raw_data else 0,
        }
        return data

    vol_data = get_volumes(query)

    # iterate volumes
    volumes_imported = 0
    for item in vol_data['items']:
        item_raw = item['volumeInfo']
        item_data = validate_item_data(item_raw)

        volume = Volume.objects.create(**item_data)

        if volume:
            if 'industryIdentifiers' in item_raw:
                for ident in item_raw['industryIdentifiers']:
                    IndustryIdentifier.objects.create(
                        type=ident['type'],
                        identifier=ident['identifier'],
                        volume=volume)

            if 'authors' in item_raw:
                for author_info in item_raw['authors']:
                    Author.objects.create(name=author_info, volume=volume)

            volumes_imported += 1

    context = {
        'volumes_imported': volumes_imported,
    }
    return render(request, 'books/import_action.html', context)


class VolumeApiView(viewsets.ModelViewSet):
    serializer_class = VolumeSerializer
    filter_backends = [SearchFilter]
    search_fields = ['title', 'authors__name', 'language', 'publishedDate']

    def get_queryset(self, *args, **kwargs):
        queryset_list = Volume.objects.all()

        q_title = self.request.GET.get('title')
        q_year = self.request.GET.get('year')
        q_author = self.request.GET.get('author')
        q_language = self.request.GET.get('language')

        if q_title:
            queryset_list = queryset_list.filter(title__icontains=q_title)

        if q_year:
            if '-' in q_year:
                y_start, y_end = q_year.split('-')
                if not y_end:
                    y_end = dt.now().year
                qfilter = Q(publishedDate__year__gte=y_start, publishedDate__year__lte=y_end)
            else:
                qfilter = Q(publishedDate__year=q_year)

            queryset_list = queryset_list.filter(qfilter)

        if q_author:
            queryset_list = queryset_list.filter(authors__name__icontains=q_author)

        if q_language:
            queryset_list = queryset_list.filter(language=q_language)

        return queryset_list

books/templates/books/add_volume.html
{% extends 'books/base.html' %}

{% block content %}

    <div id="title">
        <h2>Add a Book</h2>
    </div>

    <form method="post" id="add_book_form">
        {% csrf_token %}

        <div id="form_general">
            <h4>General Info</h4>
            {{ form.as_p }}
        </div>

        <div id="form_authors">
            <h4>Authors</h4>
            {{ formset_author.management_form }}
            {{ formset_author.as_p }}
        </div>

        <div id="form_indidents">
            <h4>Industry Identifiers</h4>
            {{ formset_indident.management_form }}
            {{ formset_indident.as_ul }}
        </div>

        <div id="form_btn_save">
            <button type="submit" class="btn btn-primary" id="save_btn">Save</button>
        </div>
    </form>

{% endblock %}

books/templates/books/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Books Manager</title>

    <link href=" {% static 'books/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'books/css/style.css' %}" rel="stylesheet">
</head>

<body>

    <div class="container">
        <div id="top" onclick="location.href = '{% url 'books:list' %}';">
            <span id="title">BOOKS MANAGER</span>
            <hr>
        </div>

        {% block content %}{% endblock %}
    </div>

    <script src="{% static 'books/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.bundle.min.js' %}"></script>

    {% block scripts %}{% endblock %}

</body>
</html>

books/templates/books/books_list.html
{% extends 'books/base.html' %}

{% block content %}

    <div id="info">
        {{ vol_count }} volumes in database
    </div>

    <div id="search">
        <form method="post">
            {% csrf_token %}
            {{ form.as_ul }}
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>

    <div id="buttons">
        <ul>
            <li><button type="button" class="btn btn-success"
                        onclick="location.href = '{% url 'books:add_volume' %}';">Add a Book</button></li>
            <li><button type="button" class="btn btn-warning"
                        onclick="location.href = '{% url 'books:import' %}'">Import Books</button></li>
        </ul>
    </div>

    {% for volume in volumes %}
        {% if forloop.first %}
        <p>Found {{ volumes.count }}/{{ vol_count }} volumes.</p>
        {% endif %}

        <h2>#{{ forloop.counter }} :: {{ volume.title }}</h2>
        <table class="table table-sm table-hover">
            <tbody>
                {% for author in volume.authors.all %}
                    {% if forloop.first %}
                        <tr><td>Authors</td>
                    {% else %}
                        <tr><td></td>
                    {% endif %}
                    <td>{{ author }}</td></tr>

                {% endfor %}

                <tr><td>Published Date</td><td>{{ volume.publishedDate }}</td></tr>
                <tr><td>Page Count</td><td>{{ volume.pageCount }}</td></tr>
                <tr><td>ImageLink Small Thumbnail</td><td><a href="{{ volume.imageLinks.smallThumbnail }}" target="_blank">{{ volume.imageLinks.smallThumbnail }}</td></tr>
                <tr><td>ImageLink Thumbnail</td><td><a href="{{ volume.imageLinks.thumbnail }}" target="_blank">{{ volume.imageLinks.thumbnail }}</td></tr>
                <tr><td>Language</td><td>{{ volume.language }}</td></tr>

                {% for ident in volume.industryIdentifiers.all %}
                    {% if forloop.first %}
                        <tr><td>Industry Identifiers</td>
                    {% else %}
                        <tr><td></td>
                    {% endif %}
                    <td>{{ ident.type }}, {{ ident.identifier }}</td></tr>
                {% endfor %}
            </tbody>
        </table>

        <br>

    {% endfor %}

{% endblock %}

books/templates/books/import.html
{% extends 'books/base.html' %}
{% load static %}

{% block content %}

    <h2>Import books</h2>

    <div id="query">
        <form method="post" id="form_query">
            {% csrf_token %}
            {{ form }}
            <button type="button" class="btn btn-primary" onclick="check();">Check</button>
            <p>(default: 10 results; &maxResults=40 possible in query)</p>
        </form>
    </div>

    <span id="info"></span>

    <div id="hidden_question">
        <p>Would you like to import volumes?</p>
        <ul>
            <li><button type="button" class="btn btn-success" onclick="do_import()">Yes</button></li>
            <li><button type="button" class="btn btn-danger" onclick="location.href='{% url 'books:import' %}';">No</button></li>
        </ul>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        let csrf_token = "{{ csrf_token }}";
    </script>

    <script src="{% static 'books/js/import_volumes.js' %}" type="text/javascript"></script>
{% endblock %}

books/templates/books/import_action.html
{% extends 'books/base.html' %}

{% block content %}
    <h2>{{ volumes_imported }} volumes imported!</h2>
{% endblock %}

{% block scripts %}
    <script>
        let timer = setTimeout(function() {
            window.location = '{% url 'books:list' %}';
        }, 3000);
    </script>
{% endblock %}